@Library('GissFwDevOps@3.8.0') _

FwDevOps("java17", "https://gitlab.pro.portal.ss/ot/mad/ot_maca_itinerario.git",
	[ 
	"MAVEN_OPTS":"-Dmaven.wagon.http.ssl.insecure=true -Dmaven.wagon.http.ssl.allowall=true -Dmaven.wagon.http.ssl.ignore.validity.dates=true",
	"XLDEPLOY_ENABLE":"false",
	"HELM_DEPLOY":"true",
	"CODE_REVIEW":"true",
	"UNIT_TEST":"true",
	"CD": "true"
    ]
)
